# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: .github
repository:
  homepage: ssh://git@gitlab.manjaro.org:22277/packages/community/gtk3-nocsd.git
# you can extend settings using https://probot.github.io/apps/settings/
